export default[
    {
        path:"/me",
        name:"个人中心",
        component:()=>import("../views/me.vue")
    },
    {
        path:"/login",
        name:"登录界面",
        component:()=>import("../components/me/login.vue")
    },
    {
        path:"/register",
        name:"注册界面",
        component:()=>import("../components/me/register.vue")
    },
    {
        path:'/address',
        name:'Address',
        component:()=>import("../components/me/address.vue")
    },
    {
        path:'/newAddress',
        name:'NewAddress',
        component:()=>import("../components/me/newAddress.vue")
    },
    {
        path:'/myInfo',
        name:'MyInfo',
        component:()=>import("../components/me/myInfo.vue")
    },
    {
        path:'/like',
        name:'Like',
        component:()=>import("../components/me/like.vue")
    }
]
